// Generated by CoffeeScript 1.4.0
(function() {

  define(['Util', 'Facebook'], function(Util, Facebook) {
    var AfterPhotos;
    AfterPhotos = (function() {

      function AfterPhotos() {}

      AfterPhotos.prototype["do"] = function(photos, albums, userId, $result) {
        var self;
        self = this;
        self.photosStats = Util.getPhotosStats(albums, photos, userId);
        Util.renderTemplate('tpl-step-7', $result, {
          photos: self.photosStats.twoBestTaggers
        });
        Util.setThisDone($result);
        Util.scrollTo($result);
        Util.fadeIn($('.need-photos'));
        $('.step-8').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayProgressBar($result);
          $result.html('You have ' + self.photosStats.numberOfPics + ' pictures');
          Util.setThisDone($result);
          return Util.scrollTo($result);
        });
        return $('.step-9').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          Util.renderTemplate('tpl-step-9', $result, {
            photos: self.photosStats.twoMostFamousPics
          });
          $(".fancybox").fancybox();
          Util.setThisDone($result);
          return Util.scrollTo($result);
        });
      };

      return AfterPhotos;

    })();
    return new AfterPhotos;
  });

}).call(this);
