// Generated by CoffeeScript 1.4.0
(function() {

  define(['Util', 'Facebook', 'fancybox', 'scrollTo'], function(Util, Facebook) {
    var AfterPhotos;
    AfterPhotos = (function() {

      function AfterPhotos() {}

      AfterPhotos.prototype["do"] = function(photos, albums, userId, $result) {
        var self;
        self = this;
        self.photosStats = Util.getPhotosStats(albums, photos, userId);
        Util.renderTemplate('tpl-step-7', $result, {
          photos: self.photosStats.twoBestTaggers
        });
        Util.setThisDone($result);
        Util.scrollTo($result);
        Util.fadeIn($('.need-photos'));
        $('.step-8').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayProgressBar($result);
          $result.html('You have ' + self.photosStats.numberOfPics + ' pictures');
          Util.setThisDone($result);
          return Util.scrollTo($result);
        });
        $('.step-9').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          Util.setThisDone($result);
          Util.renderTemplate('tpl-step-9', $result, {
            photos: self.photosStats.twoMostFamousPics
          });
          $(".fancybox").live("click", function() {
            $(this).fancybox().trigger("click");
            return false;
          });
          Util.scrollTo($result);
          return Util.fadeIn($('.need-best-photos'));
        });
        $('.step-10').click(function() {
          var checkins, events;
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          Util.setThisDone($result);
          events = Facebook.api('me/events', 'get', {
            limit: 1000,
            type: 'attending'
          });
          checkins = Facebook.api('me/checkins', 'get', {
            limit: 1000
          });
          return $.when(events, checkins).done(function(events, checkins) {
            Util.renderTemplate('tpl-step-10', $result, {
              events: events.data.length,
              checkins: checkins.data.length
            });
            Util.scrollTo($result);
            return Util.fadeIn($('.need-places'));
          }).fail(function() {
            return Util.displayErrorMsg($result);
          });
        });
        return $('.step-11').click(function() {
          return console.log('wait for it');
        });
      };

      return AfterPhotos;

    })();
    return new AfterPhotos;
  });

}).call(this);
