// Generated by CoffeeScript 1.4.0
(function() {

  define(['Util', 'Facebook', 'fancybox', 'scrollTo'], function(Util, Facebook) {
    var AfterPlaces;
    AfterPlaces = (function() {

      function AfterPlaces() {}

      AfterPlaces.prototype["do"] = function(userId, $result) {
        Util.fadeIn($('.need-best-photos'));
        Util.setThisDone($result);
        Util.scrollTo($result);
        $('.step-10').click(function() {
          var events;
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          Util.setThisDone($result);
          events = Facebook.api('me/events', 'get', {
            limit: 1000,
            type: 'attending',
            until: 1356980400
          });
          return $.when(events).done(function(events) {
            Util.renderTemplate('tpl-step-10', $result, {
              events: events.data.length
            });
            Util.scrollTo($result);
            return Util.fadeIn($('.need-places'));
          }).fail(function() {
            return Util.displayErrorMsg($result);
          });
        });
        return $('.step-11').click(function() {
          var checkins;
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          Util.setThisDone($result);
          checkins = Facebook.api('me/checkins', 'get', {
            limit: 1000
          });
          return $.when(checkins).done(function(checkins) {
            var twoFavoritePlaces;
            twoFavoritePlaces = Util.getFavoritePlaces(checkins);
            Util.renderTemplate('tpl-step-11', $result, {
              places: twoFavoritePlaces,
              checkins: checkins.data.length
            });
            Util.scrollTo($result);
            return Util.fadeIn($('#summary'));
          }).fail(function() {
            return Util.displayErrorMsg($result);
          });
        });
      };

      return AfterPlaces;

    })();
    return new AfterPlaces;
  });

}).call(this);
