// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    shim: {
      'fb-sdk': {
        exports: 'FB'
      },
      underscore: {
        exports: '_'
      }
    },
    config: {
      text: {}
    },
    paths: {
      jquery: 'lib/jquery-1.8.2.min',
      bootstrap: 'lib/bootstrap.min',
      underscore: 'lib/underscore.min',
      handlebars: 'lib/handlebars',
      fancybox: 'lib/fancybox/jquery.fancybox',
      scrollTo: 'lib/scrollTo.min',
      'fb-sdk': 'lib/fb-sdk',
      'fb-sdk-fr': '//connect.facebook.net/fr_FR/all',
      Facebook: 'Facebook',
      text: 'lib/text',
      Util: 'Util'
    },
    baseUrl: 'js/'
  });

  require(['main']);

}).call(this);
