// Generated by CoffeeScript 1.4.0
(function() {

  require(['Facebook', 'handlebars', 'underscore', 'Util', 'jquery', 'fb-sdk', 'bootstrap'], function(Facebook, Handelbars, _, Util) {
    var self;
    self = this;
    $("body").off("hover", ".done").on("mouseenter", ".done", function() {
      var question, tooltip;
      question = $(this).find('.front').find("span").html();
      tooltip = $(this).find('.tooltip');
      if (!tooltip.length) {
        $(this).append("<p class=\"tooltip\"></p>");
        $(this).find('.tooltip').html(question);
        return $(this).find('.tooltip').fadeIn(1000);
      }
    }).on("mouseleave", ".done", function() {
      var tooltip;
      tooltip = $(this).find('.tooltip');
      if (tooltip.length) {
        return $(this).find('.tooltip').remove();
      }
    });
    return $('.step-1').click(function() {
      var $result;
      $result = Util.getResultDiv(this);
      Util.displayAjaxLoader($result);
      return Facebook.login().done(function(user) {
        return require(['after-me'], function(afterMe) {
          return afterMe["do"](user, $result);
        });
      }).fail(function() {
        return Util.displayErrorMsg($result);
      });
    });
    /*$('.req-hour-post').click ->
    
      $result = Util.getResultDiv @
      Util.displayAjaxLoader $result
    
      Facebook.api('me/posts?fields=created_time', 'get',
          limit: 100
        )
        .fail(->
          Util.displayErrorMsg $result
        )
        .done((res) ->
          hourPost = Util.getHourPost(res)
          hourPostEnd = parseInt(hourPost.first.name)+1;
          hour = 'am'
          hourEnd = 'am'
          if hourPost > 12
           hourPost-= 12
           hour = 'pm'
          if hourPostEnd > 12
           hourPostEnd-= 12
           hourEnd = 'pm'
    
          $result.html '
            <ul>
              <li>Between ' + hourPost.first.name + ' ' + hour + ' and ' + hourPostEnd + ' ' + hourEnd + '</li>
            </ul>'
        )
    
    $('.req-best-status').click ->
    
      $result = Util.getResultDiv @
      Util.displayAjaxLoader $result
    
      deferred = $.Deferred()
      deferred.done (statuses) ->
    
        self.statusesStats = Util.getStatusesStats statuses
        $result.html '
          <ul>
            <li>"' + self.statusesStats.twoBestStatuses.first.name + '" (' + self.statusesStats.twoBestStatuses.first.value + ' likes)</li>
            <li>"' + self.statusesStats.twoBestStatuses.second.name + '" (' + self.statusesStats.twoBestStatuses.second.value + ' likes)</li>
          </ul>'
        $('.need-statuses').show()
    
    
        $('.req-average-like-status').click ->
          $result = Util.getResultDiv @
          Util.displayAjaxLoader $result
          Util.hasMedal('average',self.statusesStats.average)
          $result.html '<ul><li>Average : ' + self.statusesStats.average + ' likes per status</li></ul>'
    
    	    $('.req-greatest-likers-status').click ->
          $result = Util.getResultDiv @
          Util.displayAjaxLoader $result
          $result.html '
            <ul>
              <li>"' + self.statusesStats.TwoGreatestLikers.first.name + '" (' + self.statusesStats.TwoGreatestLikers.first.value + ' likes)</li>
              <li>"' + self.statusesStats.TwoGreatestLikers.second.name + '" (' + self.statusesStats.TwoGreatestLikers.second.value + ' likes)</li>
            </ul>'
    
        # Are you active ?
        $('.......').click ->
          $result = Util.getResultDiv @
          Util.displayAjaxLoader $result
          $result.html 'You post ' + self.statusesStats.statusesPerDay + ' statuses a day'
    
    
      #Util.getAllStatuses(deferred)
    */

  });

}).call(this);
