// Generated by CoffeeScript 1.4.0
(function() {

  require(['Facebook', 'handlebars', 'underscore', 'Util', 'jquery', 'fb-sdk', 'bootstrap'], function(Facebook, Handelbars, _, Util) {
    var self;
    self = this;
    $('.step-1').click(function() {
      var $result;
      $result = Util.getResultDiv(this);
      Util.displayAjaxLoader($result);
      return Facebook.login().fail(function() {
        return Util.displayErrorMsg($result);
      }).done(function(user) {
        return require(['after-me'], function(afterMe) {
          return afterMe["do"](user, $result);
        });
      });
    });
    $('.step-3').click(function() {
      var $result;
      $result = Util.getResultDiv(this);
      Util.displayAjaxLoader($result);
      return Facebook.api('me/likes', 'get', {
        limit: 100
      }).fail(function() {
        return Util.displayErrorMsg($result);
      }).done(function(res) {
        var twoBestLikeCategories;
        Util.setThisDone($result);
        twoBestLikeCategories = Util.getTwoBestLikeCategories(res);
        $result.html('\
          You like :<br>\
            ' + twoBestLikeCategories.first.name + '<br>\
            &amp; ' + twoBestLikeCategories.second.name + '');
        return Util.setThisDone($result);
      });
    });
    $('.req-hour-post').click(function() {
      var $result;
      $result = Util.getResultDiv(this);
      Util.displayAjaxLoader($result);
      return Facebook.api('me/posts?fields=created_time', 'get', {
        limit: 100
      }).fail(function() {
        return Util.displayErrorMsg($result);
      }).done(function(res) {
        var hour, hourEnd, hourPost, hourPostEnd;
        hourPost = Util.getHourPost(res);
        hourPostEnd = parseInt(hourPost.first.name) + 1;
        hour = 'am';
        hourEnd = 'am';
        if (hourPost > 12) {
          hourPost -= 12;
          hour = 'pm';
        }
        if (hourPostEnd > 12) {
          hourPostEnd -= 12;
          hourEnd = 'pm';
        }
        return $result.html('\
          <ul>\
            <li>Between ' + hourPost.first.name + ' ' + hour + ' and ' + hourPostEnd + ' ' + hourEnd + '</li>\
          </ul>');
      });
    });
    return $('.req-best-status').click(function() {
      var $result, deferred;
      $result = Util.getResultDiv(this);
      Util.displayAjaxLoader($result);
      deferred = $.Deferred();
      deferred.done(function(statuses) {
        self.statusesStats = Util.getStatusesStats(statuses);
        $result.html('\
        <ul>\
          <li>"' + self.statusesStats.twoBestStatuses.first.name + '" (' + self.statusesStats.twoBestStatuses.first.value + ' likes)</li>\
          <li>"' + self.statusesStats.twoBestStatuses.second.name + '" (' + self.statusesStats.twoBestStatuses.second.value + ' likes)</li>\
        </ul>');
        $('.need-statuses').show();
        $('.req-average-like-status').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          Util.hasMedal('average', self.statusesStats.average);
          return $result.html('<ul><li>Average : ' + self.statusesStats.average + ' likes per status</li></ul>');
        });
        $('.req-greatest-likers-status').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          return $result.html('\
          <ul>\
            <li>"' + self.statusesStats.TwoGreatestLikers.first.name + '" (' + self.statusesStats.TwoGreatestLikers.first.value + ' likes)</li>\
            <li>"' + self.statusesStats.TwoGreatestLikers.second.name + '" (' + self.statusesStats.TwoGreatestLikers.second.value + ' likes)</li>\
          </ul>');
        });
        return $('.step-2').click(function() {
          $result = Util.getResultDiv(this);
          Util.displayAjaxLoader($result);
          return $result.html('You post ' + self.statusesStats.statusesPerDay + ' statuses a day');
        });
      });
      return Util.getAllStatuses(deferred);
    });
  });

}).call(this);
