// Generated by CoffeeScript 1.3.3
(function() {

  require(['Facebook', 'handlebars', 'underscore', 'Util', 'jquery', 'fb-sdk', 'bootstrap'], function(Facebook, Handelbars, _, Util) {
    return $('h1.user').click(function() {
      return Facebook.login().fail(function() {
        return console.log('fail');
      }).done(function(user) {
        var _this = this;
        this.userId = user.id;
        $('#profile-pic').html('<img src="http://graph.facebook.com/' + user.username + '/picture" atl="" height="40" />');
        $('#user').html('<p>Hey ' + user.name + '... Let\'s see your secrets...</p>');
        Facebook.api('me/likes', 'get', {
          limit: 100
        }).fail(function() {
          return console.log('fail');
        }).done(function(res) {
          var twoBestLikeCategories;
          twoBestLikeCategories = Util.getTwoBestLikeCategories(res);
          return $('body').append('<p>It looks like you have passion for "' + twoBestLikeCategories.first.name + '" and "' + twoBestLikeCategories.second.name + '".</p>');
        });
        Facebook.api('me/friends', 'get', {
          limit: 100
        }).fail(function() {
          return console.log('fail');
        }).done(function(res) {
          var postId;
          console.log(res);
          return postId = res.data[0].id;
        });
        return Facebook.api('me/photos', 'get', {
          limit: 1000
        }).fail(function() {
          return console.log('fail');
        }).done(function(res) {
          var twoBestTaggers;
          twoBestTaggers = Util.getTwoBestTaggers(res, _this.userId);
          return $('body').append('<p>People who have tagged you : "' + twoBestTaggers.first.name + '" and "' + twoBestTaggers.second.name + '".</p>');
        });
      });
    });
  });

}).call(this);
